version: '3.8'

services:
    drf-db:
        image: postgres:13.7
        hostname: drf-db
        container_name: drf-db
        privileged: true
        restart: always
        env_file: ./backend/config/.env
        expose:
            - 5432
        volumes:
            - ./backend/data/pg_data:/var/lib/postgresql/data/
            - ./backend/scripts/database-init.sh:/docker-entrypoint-initdb.d/init-database.sh

    drf-backend:
        build: ./backend
        hostname: drf-backend
        container_name: drf-backend
        privileged: true
        restart: always
        env_file: ./backend/config/.env
        expose:
            - 8000
        entrypoint: ./scripts/backend-init.sh
        command:
            - '/bin/sh'
            - '-c'
            # - './manage.py runserver 0.0.0.0:8000 --insecure'
            - gunicorn --access-logfile - --workers 2 --bind 0.0.0.0:8000 config.wsgi
        depends_on:
            - drf-db

    drf-nginx:
        build: ./nginx
        hostname: drf-nginx
        container_name: drf-nginx
        privileged: true
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./backend/static/:/var/www/static/
        depends_on:
            - drf-backend

    drf-frontend:
        build: ./frontend
        hostname: drf-frontend
        container_name: drf-frontend
        privileged: true
        restart: always
        ports:
            - 80:80
        depends_on:
            - drf-nginx

    drf-adminer:
        image: adminer:4.7.8-standalone
        hostname: drf-adminer
        container_name: drf-adminer
        privileged: false
        restart: always
        env_file: ./backend/config/.env
        ports:
            - 8080:8080
        depends_on:
            - drf-db
