# Generated by Django 3.2.15 on 2022-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("repo", models.CharField(blank=True, default=None, max_length=255, verbose_name="repo")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("text", models.CharField(max_length=1000, verbose_name="title")),
                ("is_completed", models.BooleanField(default=False, verbose_name="is_completed")),
            ],
            options={
                "verbose_name": "ToDo",
                "verbose_name_plural": "ToDos",
                "ordering": ("-created",),
            },
        ),
    ]
