#!/bin/bash

set -e

echo ""
echo " --> BEGIN DB INITIALIZATION..."
echo ""

psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER <<-EOSQL
    CREATE USER $DJANGO_DB_USER WITH PASSWORD '$DJANGO_DB_PASSWORD';
    CREATE DATABASE $DJANGO_DB_NAME WITH ENCODING = 'utf8' OWNER = $DJANGO_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DB_NAME TO $DJANGO_DB_USER;
    ALTER ROLE $DJANGO_DB_USER SET CLIENT_ENCODING TO 'UTF8';
    ALTER ROLE $DJANGO_DB_USER SET default_transaction_isolation TO 'READ COMMITTED';
EOSQL
